name: tf-checks
on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  tf-static-checks:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './_examples/complete/'